indentation fixes and clang-option-check changed in pacman/makepkg.conf

diff --git a/core/pacman/Makepkg_new-functions.patch b/core/pacman/Makepkg_new-functions.patch
--- a/core/pacman/Makepkg_new-functions.patch
+++ b/core/pacman/Makepkg_new-functions.patch
@@ -30,18 +30,16 @@
  	# use distcc if it is requested (check buildenv and PKGBUILD opts)
  	if check_buildenv "distcc" "y" && ! check_option "distcc" "n"; then
  		[[ -d /usr/lib/distcc/bin ]] && export PATH="/usr/lib/distcc/bin:$PATH"
-@@ -1495,6 +1506,15 @@
+@@ -1495,6 +1506,13 @@
  		[[ -d /usr/lib/ccache/bin ]] && export PATH="/usr/lib/ccache/bin:$PATH"
  	fi
  
 +	# Set our compiler
-+  if check_buildenv "clang" "y" && ! check_option "clang" "n"; then
++	if check_buildenv "clang" "y" && ! check_option "clang" "n"; then
 +		run_function_safe set_compiler_clang
-+  fi
-+
-+  if check_buildenv "clang" "y" && ! check_option "clang" "y"; then
-+    run_function_safe set_compiler_gcc
-+  fi
++	else
++		run_function_safe set_compiler_gcc
++	fi
 +
  	run_function_safe "build"
  }
@@ -54,11 +52,11 @@
 +ABSD_FUNCTIONS=${ABSD_FUNCTIONS:-$absddir/absd-functions}
 +
 +if [[ -r $ABSD_FUNCTIONS ]]; then
-+        source_safe "$ABSD_FUNCTIONS"
++	source_safe "$ABSD_FUNCTIONS"
 +else
-+        error "$(gettext "%s not found.")" "$ABSD_FUNCTIONS"
-+        plain "$(gettext "Aborting...")"
-+        exit 1 # $E_CONFIG_ERROR
++	error "$(gettext "%s not found.")" "$ABSD_FUNCTIONS"
++	plain "$(gettext "Aborting...")"
++	exit 1 # $E_CONFIG_ERROR
 +fi
 +
 +
